spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: 1019
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    enabled: true
    contexts: dev

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        hbm2ddl:
          auto: validate
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      header: auth-token